site_name: geoscience semantics

repo_url: https://github.com/geoscience-semantics/geoscience-semantics.github.io
repo_name:
site_description: awesome geoscience semantic models
site_author: brandon whitehead

pages:
- home: index.md
- ontology rundown: ontologies.md
- references: 'refs.md'
- about:
    - 'introduction to <br />geoscience semantic models': 'intro.md'
    - 'other resources': 'resources.md'
    - '*notes': 'notes.md'
    - 'contribute': 'contributing.md'

theme: yeti
